/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintDispensingStoreIdRouteImport } from './routes/print.dispensing.$storeId'
import { Route as PrintBalanceStoreIdRouteImport } from './routes/print.balance.$storeId'

const PrintDispensingStoreIdRoute = PrintDispensingStoreIdRouteImport.update({
  id: '/print/dispensing/$storeId',
  path: '/print/dispensing/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintBalanceStoreIdRoute = PrintBalanceStoreIdRouteImport.update({
  id: '/print/balance/$storeId',
  path: '/print/balance/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/print/balance/$storeId': typeof PrintBalanceStoreIdRoute
  '/print/dispensing/$storeId': typeof PrintDispensingStoreIdRoute
}
export interface FileRoutesByTo {
  '/print/balance/$storeId': typeof PrintBalanceStoreIdRoute
  '/print/dispensing/$storeId': typeof PrintDispensingStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/print/balance/$storeId': typeof PrintBalanceStoreIdRoute
  '/print/dispensing/$storeId': typeof PrintDispensingStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/print/balance/$storeId' | '/print/dispensing/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/print/balance/$storeId' | '/print/dispensing/$storeId'
  id: '__root__' | '/print/balance/$storeId' | '/print/dispensing/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrintBalanceStoreIdRoute: typeof PrintBalanceStoreIdRoute
  PrintDispensingStoreIdRoute: typeof PrintDispensingStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/print/dispensing/$storeId': {
      id: '/print/dispensing/$storeId'
      path: '/print/dispensing/$storeId'
      fullPath: '/print/dispensing/$storeId'
      preLoaderRoute: typeof PrintDispensingStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/balance/$storeId': {
      id: '/print/balance/$storeId'
      path: '/print/balance/$storeId'
      fullPath: '/print/balance/$storeId'
      preLoaderRoute: typeof PrintBalanceStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PrintBalanceStoreIdRoute: PrintBalanceStoreIdRoute,
  PrintDispensingStoreIdRoute: PrintDispensingStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
