/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQaRouteImport } from './routes/_authenticated/qa'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedImportExportRouteImport } from './routes/_authenticated/import-export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBarcodesRouteImport } from './routes/_authenticated/barcodes'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedWarehousesNewRouteImport } from './routes/_authenticated/warehouses.new'
import { Route as AuthenticatedWarehousesIdRouteImport } from './routes/_authenticated/warehouses.$id'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQaRoute = AuthenticatedQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportExportRoute =
  AuthenticatedImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBarcodesRoute = AuthenticatedBarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWarehousesNewRoute =
  AuthenticatedWarehousesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedWarehousesRoute,
  } as any)
const AuthenticatedWarehousesIdRoute =
  AuthenticatedWarehousesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWarehousesRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/barcodes': typeof AuthenticatedBarcodesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/qa': typeof AuthenticatedQaRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRouteWithChildren
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/warehouses/$id': typeof AuthenticatedWarehousesIdRoute
  '/warehouses/new': typeof AuthenticatedWarehousesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/barcodes': typeof AuthenticatedBarcodesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/qa': typeof AuthenticatedQaRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRouteWithChildren
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/warehouses/$id': typeof AuthenticatedWarehousesIdRoute
  '/warehouses/new': typeof AuthenticatedWarehousesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/barcodes': typeof AuthenticatedBarcodesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import-export': typeof AuthenticatedImportExportRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/qa': typeof AuthenticatedQaRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRouteWithChildren
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/warehouses/$id': typeof AuthenticatedWarehousesIdRoute
  '/_authenticated/warehouses/new': typeof AuthenticatedWarehousesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/backups'
    | '/barcodes'
    | '/dashboard'
    | '/import-export'
    | '/inventory'
    | '/notifications'
    | '/products'
    | '/qa'
    | '/reports'
    | '/settings'
    | '/users'
    | '/warehouses'
    | '/products/$id'
    | '/products/new'
    | '/warehouses/$id'
    | '/warehouses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/backups'
    | '/barcodes'
    | '/dashboard'
    | '/import-export'
    | '/inventory'
    | '/notifications'
    | '/products'
    | '/qa'
    | '/reports'
    | '/settings'
    | '/users'
    | '/warehouses'
    | '/products/$id'
    | '/products/new'
    | '/warehouses/$id'
    | '/warehouses/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/audit-logs'
    | '/_authenticated/backups'
    | '/_authenticated/barcodes'
    | '/_authenticated/dashboard'
    | '/_authenticated/import-export'
    | '/_authenticated/inventory'
    | '/_authenticated/notifications'
    | '/_authenticated/products'
    | '/_authenticated/qa'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/warehouses'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/new'
    | '/_authenticated/warehouses/$id'
    | '/_authenticated/warehouses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa': {
      id: '/_authenticated/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AuthenticatedQaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import-export': {
      id: '/_authenticated/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AuthenticatedImportExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/barcodes': {
      id: '/_authenticated/barcodes'
      path: '/barcodes'
      fullPath: '/barcodes'
      preLoaderRoute: typeof AuthenticatedBarcodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouses/new': {
      id: '/_authenticated/warehouses/new'
      path: '/new'
      fullPath: '/warehouses/new'
      preLoaderRoute: typeof AuthenticatedWarehousesNewRouteImport
      parentRoute: typeof AuthenticatedWarehousesRoute
    }
    '/_authenticated/warehouses/$id': {
      id: '/_authenticated/warehouses/$id'
      path: '/$id'
      fullPath: '/warehouses/$id'
      preLoaderRoute: typeof AuthenticatedWarehousesIdRouteImport
      parentRoute: typeof AuthenticatedWarehousesRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
  }
}

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedWarehousesRouteChildren {
  AuthenticatedWarehousesIdRoute: typeof AuthenticatedWarehousesIdRoute
  AuthenticatedWarehousesNewRoute: typeof AuthenticatedWarehousesNewRoute
}

const AuthenticatedWarehousesRouteChildren: AuthenticatedWarehousesRouteChildren =
  {
    AuthenticatedWarehousesIdRoute: AuthenticatedWarehousesIdRoute,
    AuthenticatedWarehousesNewRoute: AuthenticatedWarehousesNewRoute,
  }

const AuthenticatedWarehousesRouteWithChildren =
  AuthenticatedWarehousesRoute._addFileChildren(
    AuthenticatedWarehousesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedBarcodesRoute: typeof AuthenticatedBarcodesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportExportRoute: typeof AuthenticatedImportExportRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedQaRoute: typeof AuthenticatedQaRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedBarcodesRoute: AuthenticatedBarcodesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportExportRoute: AuthenticatedImportExportRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedQaRoute: AuthenticatedQaRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
